/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author otoniel.aalves
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jRadioButtonMenuItem12 = new javax.swing.JRadioButtonMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem13 = new javax.swing.JRadioButtonMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem14 = new javax.swing.JRadioButtonMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem15 = new javax.swing.JRadioButtonMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem16 = new javax.swing.JRadioButtonMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem17 = new javax.swing.JRadioButtonMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem18 = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jRadioButtonMenuItem9 = new javax.swing.JRadioButtonMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem10 = new javax.swing.JRadioButtonMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem11 = new javax.swing.JRadioButtonMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem7 = new javax.swing.JRadioButtonMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem8 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(720, 28));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arquivos.png"))); // NOI18N
        jMenu1.setText("Arquivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu1.setMinimumSize(new java.awt.Dimension(81, 32767));
        jMenu1.setPreferredSize(new java.awt.Dimension(120, 24));

        jRadioButtonMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonMenuItem1.setText("Troca de Senha");
        jRadioButtonMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/trocarsenha1.png"))); // NOI18N
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);
        jMenu1.add(jSeparator1);

        jRadioButtonMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonMenuItem2.setText("Troca de Usuário");
        jRadioButtonMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/trocaUser.png"))); // NOI18N
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem2);
        jMenu1.add(jSeparator2);

        jRadioButtonMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonMenuItem3.setText("Sair");
        jRadioButtonMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro.png"))); // NOI18N
        jMenu8.setText("Cadastro");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(120, 24));

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jMenu9.setText("Produto");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jRadioButtonMenuItem12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonMenuItem12.setSelected(true);
        jRadioButtonMenuItem12.setText("Produto");
        jRadioButtonMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jRadioButtonMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem12ActionPerformed(evt);
            }
        });
        jMenu9.add(jRadioButtonMenuItem12);
        jMenu9.add(jSeparator9);

        jRadioButtonMenuItem13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonMenuItem13.setSelected(true);
        jRadioButtonMenuItem13.setText("Categoria");
        jRadioButtonMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/categoria.png"))); // NOI18N
        jRadioButtonMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem13ActionPerformed(evt);
            }
        });
        jMenu9.add(jRadioButtonMenuItem13);
        jMenu9.add(jSeparator10);

        jRadioButtonMenuItem14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonMenuItem14.setSelected(true);
        jRadioButtonMenuItem14.setText("Unidade de Medida");
        jRadioButtonMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/medida.png"))); // NOI18N
        jRadioButtonMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem14ActionPerformed(evt);
            }
        });
        jMenu9.add(jRadioButtonMenuItem14);

        jMenu8.add(jMenu9);
        jMenu8.add(jSeparator11);

        jRadioButtonMenuItem15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonMenuItem15.setText("Fornecedor");
        jRadioButtonMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor.png"))); // NOI18N
        jRadioButtonMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem15ActionPerformed(evt);
            }
        });
        jMenu8.add(jRadioButtonMenuItem15);
        jMenu8.add(jSeparator12);

        jRadioButtonMenuItem16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonMenuItem16.setText("Setor / Localidade");
        jRadioButtonMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/local.png"))); // NOI18N
        jRadioButtonMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem16ActionPerformed(evt);
            }
        });
        jMenu8.add(jRadioButtonMenuItem16);
        jMenu8.add(jSeparator13);

        jRadioButtonMenuItem17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonMenuItem17.setText("Entrada");
        jRadioButtonMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/entrada_1.png"))); // NOI18N
        jRadioButtonMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem17ActionPerformed(evt);
            }
        });
        jMenu8.add(jRadioButtonMenuItem17);
        jMenu8.add(jSeparator14);

        jRadioButtonMenuItem18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonMenuItem18.setText("Saída");
        jRadioButtonMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/171.png"))); // NOI18N
        jRadioButtonMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem18ActionPerformed(evt);
            }
        });
        jMenu8.add(jRadioButtonMenuItem18);

        jMenuBar1.add(jMenu8);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        jMenu3.setText("Consulta");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(120, 24));

        jMenu7.setText("Material");

        jRadioButtonMenuItem9.setSelected(true);
        jRadioButtonMenuItem9.setText("Material");
        jMenu7.add(jRadioButtonMenuItem9);
        jMenu7.add(jSeparator5);

        jRadioButtonMenuItem10.setSelected(true);
        jRadioButtonMenuItem10.setText("Categoria");
        jRadioButtonMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem10);
        jMenu7.add(jSeparator6);

        jRadioButtonMenuItem11.setSelected(true);
        jRadioButtonMenuItem11.setText("Unidade de Medida");
        jRadioButtonMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem11ActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem11);

        jMenu3.add(jMenu7);
        jMenu3.add(jSeparator3);

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("Fornecedor");
        jMenu3.add(jRadioButtonMenuItem5);
        jMenu3.add(jSeparator4);

        jRadioButtonMenuItem6.setSelected(true);
        jRadioButtonMenuItem6.setText("Setor");
        jMenu3.add(jRadioButtonMenuItem6);
        jMenu3.add(jSeparator7);

        jRadioButtonMenuItem7.setSelected(true);
        jRadioButtonMenuItem7.setText("Entrada");
        jRadioButtonMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem7);
        jMenu3.add(jSeparator8);

        jRadioButtonMenuItem8.setSelected(true);
        jRadioButtonMenuItem8.setText("Saída");
        jMenu3.add(jRadioButtonMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/trocarsenha1.png"))); // NOI18N
        jMenu4.setText("Acesso");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(120, 24));

        jRadioButtonMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("Usuário Acesso ao Sistema");
        jRadioButtonMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/userr.png"))); // NOI18N
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logs.png"))); // NOI18N
        jMenu5.setText("Logs");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(120, 24));
        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logis.png"))); // NOI18N
        jMenu6.setText("Ajuda");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(120, 24));
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
        // TODO add your handling code here:
        new FrmUsuario().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        // TODO add your handling code here:
        new FrmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem10ActionPerformed
        // TODO add your handling code here:
        new FrmCategoria().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem10ActionPerformed

    private void jRadioButtonMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem11ActionPerformed
        // TODO add your handling code here:
        new FrmUnidadeMedida().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem11ActionPerformed

    private void jRadioButtonMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem13ActionPerformed
        // TODO add your handling code here:
        new FrmCategoria().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem13ActionPerformed

    private void jRadioButtonMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem14ActionPerformed
        // TODO add your handling code here:
        new FrmUnidadeMedida().setVisible(true);

    }//GEN-LAST:event_jRadioButtonMenuItem14ActionPerformed

    private void jRadioButtonMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem16ActionPerformed
        // TODO add your handling code here:
        new FrmSetor().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem16ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
        new FrmTrocarSenha().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem15ActionPerformed
        // TODO add your handling code here:
        new FrmFornecedor().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem15ActionPerformed

    private void jRadioButtonMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem12ActionPerformed
        // TODO add your handling code here:
        new FrmProduto().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem12ActionPerformed

    private void jRadioButtonMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem7ActionPerformed
        // TODO add your handling code here:
        new FrmEntradaConsulta().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem7ActionPerformed

    private void jRadioButtonMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem17ActionPerformed
         // TODO add your handling code here:
         new FrmEntrada().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem17ActionPerformed

    private void jRadioButtonMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem18ActionPerformed
         // TODO add your handling code here:
         
         
    }//GEN-LAST:event_jRadioButtonMenuItem18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem10;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem11;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem12;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem13;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem14;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem15;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem16;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem17;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem18;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem8;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
